### ISSUE TITLE
Redefined local `args`

### ISSUE THREAD

**Issue by uga-rosa** [hrsh7th/nvim-kit#12]
Failed in luacheck.
https://github.com/hrsh7th/nvim-kit/blob/3c7435415918dd57ee7823f0c233ec51cea97977/lua/___kit___/kit/Thread/Worker.lua#L21-L23

**Comment by uga-rosa** [comment]
It's not merged into the main branch, is it ok to close it?

**Comment by hrsh7th** [comment]
Sorry! I did the wrong git operation.

I think now the branch was merged correctly.
